export enum Profession {
    AGRICULTURAL_TECHNICIAN = 18,
    FARMER = 19,
    FERTILIZER_DEALER_SELLER = 5,
    LOAN_OFFICER = 4,
    RESEARCHER = 3,
    UNIVERSITY_PROFESSOR_INSTRUCTOR = 16,
    STUDENT = 17,
    OTHERS = 6,
}
