export enum FiveCmIrrigationDept {
    BASE64IMG = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAIAAAADnC86AAAAA3NCSVQICAjb4U/gAAAAX3pUWHRSYXcgcHJvZmlsZSB0eXBlIEFQUDEAAAiZ40pPzUstykxWKCjKT8vMSeVSAANjEy4TSxNLo0QDAwMLAwgwNDAwNgSSRkC2OVQo0QAFmJibpQGhuVmymSmIzwUAT7oVaBst2IwAAABVSURBVFiF7daxDcAwCERRsLIiNyRL4gFiRUpjCv61gJ6QKPCqso6sFhUYGBgYGPgrHhEtcNvGj5ll5rsg6ThwbP7bL2necXHV1+K8t8DAwMDAwHPhDf6nEUcl8bN1AAAAAElFTkSuQmCC",
    HEADER = "Keep flood water below 5 cm depth",
    BODY = "",
}