export enum Region {
	CAR = 1,
	REGION_I = 2,
	REGION_II = 3,
	REGION_III = 4,
	CALABARZON = 5,
	MIMAROPA = 6,
	REGION_V = 7,
	REGION_VI = 8,
	REGION_VII = 9,
	REGION_VIII = 10,
	REGION_IX = 11,
	REGION_X = 12,
	REGION_XI = 13,
	REGION_XII = 14,
	ARMM = 15,
	REGION_XIII = 16

}