export const EARLY_TRANSPLANTING_GROWTH_DAYS = 110;
export const MIDDLE_TRANSPLANTING_GROWTH_DAYS = 120;
export const LATE_TRANSPLANTING_GROWTH_DAYS = 130;

export const EARLY_GROWTH_DAYS = 100;
export const MIDDLE_GROWTH_DAYS = 110;
export const LATE_GROWTH_DAYS = 120;