export const offlineDBkey = {
	FARMER_KEY_PREFIX: 'FARMER_STORAGE_KEY',
	FARMER_LOCATION_KEY_PREFIX: 'FARMER_LOCATION_STORAGE_KEY',
	FIELD_KEY_PREFIX: 'FIELD_STORAGE_KEY',
	RECOMMENDATIONS_KEY_PREFIX: 'RECOMMENDATION_STORAGE_KEY',
	FIELD_RECOMMENDATIONS_KEY_PREFIX: 'RECOMMENDATION_'
}