export enum FarmerType {
    LOCAL_FARMER_TECHNICIAN = 2,
    FARMER_LED_EXTENSIONIST = 3,
    TECHNO_DEMO_FARMER_COOPERATOR = 4,
    SEED_GROWER = 5,
    TYPICAL_FARMER = 7,
    OTHER_FARMER_TYPE = 6
}